# Generated by Django 4.1.1 on 2022-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
