# Generated by Django 4.1.1 on 2022-09-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_customer_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userpic',
            field=models.ImageField(blank=True, default='media/profile_image/default.png', upload_to='profile_image'),
        ),
    ]
