# Generated by Django 4.1.1 on 2022-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_customer_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userpic',
            field=models.ImageField(blank=True, default='profile_image/default.png', upload_to='profile_image'),
        ),
    ]
